/**
 * Dados mestres por curso — porta fiel de `sistema_calendario/cursos_master.yaml`
 * para TypeScript. Ver o cabeçalho do .yaml (fonte da verdade) para a
 * metodologia completa: como cada campo foi obtido, e as lacunas conhecidas
 * (curso RH ordem 2 sem disciplina; curso GD fora da lista, cancelado).
 * Regenerar os dois arquivos juntos quando a planilha mudar.
 */

export interface DisciplinaCarrossel {
  ordem: number;
  disciplina: string | null;
  codigoDisciplina: string | null;
  tipoOferta: string | null;
  ch: number | null;
  liveEstudoCasoOffset: number | null;
  liveFechamentoOffset: number | null;
}

export interface CursoMaster {
  sigla: string;
  curso: string;
  diaSemanaDefault: "quinta" | "quarta";
  paCh: number;
  paAnosElegiveis: number[];
  paCodigoPrefixo: string;
  carrossel: DisciplinaCarrossel[];
}

export const CURSOS_MASTER: Record<string, CursoMaster> = {
  "411-1000": {
    sigla: "IS",
    curso: "Inteligência Artificial na Saúde: Eficiência, Soluções e Ética",
    diaSemanaDefault: "quarta",
    paCh: 60,
    paAnosElegiveis: [2026, 2027, 2028],
    paCodigoPrefixo: "41130020012",
    carrossel: [
      { ordem: 1, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: null },
      { ordem: 2, disciplina: "Estratégias de Mercado para Soluções de IA", codigoDisciplina: "41130010045", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 3, disciplina: "Engenharia de Prompt: Bons Comandos para Melhores Respostas da IA", codigoDisciplina: "41130010042", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 4, disciplina: "Gestão de Dados em Saúde: LLMS e Insights Baseados em Big Data", codigoDisciplina: "41130010058", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 5, disciplina: "IA Generativa no Apoio à Decisão Clínica: Eficiência e Ética", codigoDisciplina: "41130010008", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 6, disciplina: "A Revolução da Inteligência Artificial e Suas Aplicações", codigoDisciplina: "41130010006", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 7, disciplina: "Automação e Monitoramento Remoto com IoT e Wearables", codigoDisciplina: "41130010019", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 8, disciplina: "O Que é o Virtual? Entendendo o Ciberespaço", codigoDisciplina: "41130010101", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 9, disciplina: "Aplicativos e Algoritmos de Inteligência Artificial em Prol de Estratégias em Serviços de Saúde Mental", codigoDisciplina: "41130010013", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 10, disciplina: "Arquitetura Big Data: Como Potencializar As Análises e Tomada De Decisões Ágeis", codigoDisciplina: "41130010014", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 11, disciplina: "Gestão da Experiência do Cliente na Saúde Digital", codigoDisciplina: "41130010057", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 12, disciplina: "Tecnologias Emergentes na Saúde", codigoDisciplina: "41130010124", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 13, disciplina: "Gestão de Produtos de IA: O Ciclo de Vida de Produtos com IA, da Concepção ao Lançamento", codigoDisciplina: "41130010061", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 14, disciplina: "Inovação Tecnológica e Transformação Digital: Impacto e Estratégias", codigoDisciplina: "41130010072", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 15, disciplina: "Ética: Inteligência Moral na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
    ],
  },
  "411-1005": {
    sigla: "IA",
    curso: "IA e Negócios: Estratégia, Inovação e Resultados",
    diaSemanaDefault: "quarta",
    paCh: 60,
    paAnosElegiveis: [2026, 2027, 2028],
    paCodigoPrefixo: "41130020013",
    carrossel: [
      { ordem: 1, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: null },
      { ordem: 2, disciplina: "Ética e Privacidade na Era da Inteligência Artificial", codigoDisciplina: "41130010047", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 3, disciplina: "Gestão de Produtos de IA: O Ciclo de Vida de Produtos com IA, da Concepção ao Lançamento", codigoDisciplina: "41130010061", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 4, disciplina: "Visão Estratégica: Incorporando Soluções de IA via Marketplace de APIs", codigoDisciplina: "41130010131", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 5, disciplina: "A Revolução da Inteligência Artificial e Suas Aplicações", codigoDisciplina: "41130010006", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 6, disciplina: "Inteligência Artificial", codigoDisciplina: "41130010074", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 7, disciplina: "Projetos com IA: Design, Execução e Avaliação de Impacto", codigoDisciplina: "41130010114", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 8, disciplina: "Experiências do Cliente e IA: Personalização em Larga Escala", codigoDisciplina: "41130010049", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 9, disciplina: "Governança em Inteligência Artificial", codigoDisciplina: "41130010065", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 10, disciplina: "Ciência de Dados: Agile Data Science Escalável", codigoDisciplina: "41130010029", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 11, disciplina: "Big Data e Estratégias de Dados: O Enriquecimento de Bases como Estratégia Competitiva", codigoDisciplina: "41130010022", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 12, disciplina: "Engenharia de Prompt e Interação com Modelos de IA Generativa", codigoDisciplina: "41130010041", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 13, disciplina: "Liderança e Inovação com IA: Promovendo Inovação por Meio de IA", codigoDisciplina: "41130010082", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 14, disciplina: "Inovação Tecnológica e Transformação Digital: Impacto e Estratégias", codigoDisciplina: "41130010072", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 15, disciplina: "Ética: Inteligência Moral na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
    ],
  },
  "411-1020": {
    sigla: "RH",
    curso: "RH & IA: Gestão Humana Data-Driven",
    diaSemanaDefault: "quinta",
    paCh: 72,
    paAnosElegiveis: [2027, 2028],
    paCodigoPrefixo: "41130020014",
    carrossel: [
      { ordem: 1, disciplina: "Raciocínio Lógico e Formulação de Hipóteses com IA", codigoDisciplina: "41130010176", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 2, disciplina: null, codigoDisciplina: null, tipoOferta: null, ch: null, liveEstudoCasoOffset: null, liveFechamentoOffset: null }, // LACUNA CONHECIDA na planilha original
      { ordem: 3, disciplina: "Pensamento Crítico e Tomada de Decisão Baseada em Dados e IA", codigoDisciplina: "41130010177", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 4, disciplina: "Análise Preditiva de Talentos e Performance", codigoDisciplina: "41130010183", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 5, disciplina: "IA Generativa e Criatividade Aplicada", codigoDisciplina: "41130010178", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 6, disciplina: "Recrutamento e Seleção Inteligentes com IA", codigoDisciplina: "41130010184", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 7, disciplina: "Automação Inteligente, Produtividade e Bem-Estar com IA", codigoDisciplina: "41130010179", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 8, disciplina: "Remuneração, Benefícios e Orçamento Estratégico com IA", codigoDisciplina: "41130010185", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 9, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010180", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: null },
      { ordem: 10, disciplina: "Experiência do Colaborador Aumentada com IA", codigoDisciplina: "41130010186", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 11, disciplina: "Ética", codigoDisciplina: "41130010181", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 12, disciplina: "Implementação Estratégica de IA para RH", codigoDisciplina: "41130010187", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
    ],
  },
  "411-1021": {
    sigla: "IL",
    curso: "Inteligência Artificial para Liderança e Gestão",
    diaSemanaDefault: "quinta",
    paCh: 72,
    paAnosElegiveis: [2027, 2028],
    paCodigoPrefixo: "41130020015",
    carrossel: [
      { ordem: 1, disciplina: "Raciocínio Lógico e Formulação de Hipóteses com IA", codigoDisciplina: "41130010176", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 2, disciplina: "Inovação e Experimentação com IA", codigoDisciplina: "41130010188", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 3, disciplina: "Pensamento Crítico e Tomada de Decisão Baseada em Dados e IA", codigoDisciplina: "41130010177", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 4, disciplina: "Liderança Híbrido Humano-IA", codigoDisciplina: "41130010189", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 5, disciplina: "IA Generativa e Criatividade Aplicada", codigoDisciplina: "41130010178", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 6, disciplina: "Estratégia Empresarial Aumentada por IA", codigoDisciplina: "41130010190", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 7, disciplina: "Automação Inteligente, Produtividade e Bem-Estar com IA", codigoDisciplina: "41130010179", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 8, disciplina: "ROI e Impacto Financeiro da IA Aplicada", codigoDisciplina: "41130010203", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 9, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010180", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: null },
      { ordem: 10, disciplina: "Arquitetura Organizacional Adaptativa na Era da IA", codigoDisciplina: "41130010204", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 11, disciplina: "Ética", codigoDisciplina: "41130010181", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 12, disciplina: "Gestão da Mudança em Iniciativas de IA", codigoDisciplina: "41130010205", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
    ],
  },
  "411-1022": {
    sigla: "IK",
    curso: "Inteligência Artificial para o Marketing Estratégico",
    diaSemanaDefault: "quinta",
    paCh: 72,
    paAnosElegiveis: [2027, 2028],
    paCodigoPrefixo: "41130020016",
    carrossel: [
      { ordem: 1, disciplina: "Raciocínio Lógico e Formulação de Hipóteses com IA", codigoDisciplina: "41130010176", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 2, disciplina: "Marketing Preditivo e Agentes Inteligentes", codigoDisciplina: "41130010191", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 3, disciplina: "Pensamento Crítico e Tomada de Decisão Baseada em Dados e IA", codigoDisciplina: "41130010177", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 4, disciplina: "Inteligência de Mercado orientada por IA", codigoDisciplina: "41130010192", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 5, disciplina: "IA Generativa e Criatividade Aplicada", codigoDisciplina: "41130010178", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 6, disciplina: "IA Generativa e Automação de Conteúdo em Marketing", codigoDisciplina: "41130010193", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 7, disciplina: "Automação Inteligente, Produtividade e Bem-Estar com IA", codigoDisciplina: "41130010179", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 8, disciplina: "Mídia Paga e Campanhas Otimizadas com IA", codigoDisciplina: "41130010200", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 9, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010180", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: null },
      { ordem: 10, disciplina: "Estratégias de Mercado para Soluções de IA", codigoDisciplina: "41130010201", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 11, disciplina: "Ética", codigoDisciplina: "41130010181", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 12, disciplina: "Hiperpersonalização em Tempo Real com IA", codigoDisciplina: "41130010202", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
    ],
  },
  "411-1023": {
    sigla: "CE",
    curso: "Customer Experience e IA: Transformando a Jornada do Cliente",
    diaSemanaDefault: "quinta",
    paCh: 72,
    paAnosElegiveis: [2027, 2028],
    paCodigoPrefixo: "41130020017",
    carrossel: [
      { ordem: 1, disciplina: "Raciocínio Lógico e Formulação de Hipóteses com IA", codigoDisciplina: "41130010176", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 2, disciplina: "Customer Analytics com IA para Tomada de Decisões", codigoDisciplina: "41130010194", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 3, disciplina: "Pensamento Crítico e Tomada de Decisão Baseada em Dados e IA", codigoDisciplina: "41130010177", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 4, disciplina: "Assistentes Virtuais e Interações Conversacionais com IA", codigoDisciplina: "41130010195", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 5, disciplina: "IA Generativa e Criatividade Aplicada", codigoDisciplina: "41130010178", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 6, disciplina: "Governança de Dados do Cliente e IA Responsável", codigoDisciplina: "41130010196", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 7, disciplina: "Automação Inteligente, Produtividade e Bem-Estar com IA", codigoDisciplina: "41130010179", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 8, disciplina: "Análise Preditiva do Comportamento do Cliente com IA", codigoDisciplina: "41130010198", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 9, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010180", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: null },
      { ordem: 10, disciplina: "Design de Experiências Inteligentes e UX Multissensorial com IA", codigoDisciplina: "41130010197", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 11, disciplina: "Ética", codigoDisciplina: "41130010181", tipoOferta: "C", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 12, disciplina: "Personalização Omnichannel e Motores de Recomendação com IA", codigoDisciplina: "41130010199", tipoOferta: "A", ch: 24, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
    ],
  },
  "411-393": {
    sigla: "SM",
    curso: "Saúde Mental e Desenvolvimento Humano",
    diaSemanaDefault: "quinta",
    paCh: 60,
    paAnosElegiveis: [2026, 2027, 2028],
    paCodigoPrefixo: "41130020001",
    carrossel: [
      { ordem: 1, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: null },
      { ordem: 2, disciplina: "Práticas Integrativas Complementares em Saúde Mental na Atenção Primária em Saúde", codigoDisciplina: "41130010111", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 3, disciplina: "Sociabilização e Emoções na Neurodivergência", codigoDisciplina: "41130010136", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 4, disciplina: "Vulnerabilidades Psicológicas na Infância e Juventude do Século XXI", codigoDisciplina: "41130010132", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 5, disciplina: "A Questão do Gênero no Século XXI: A Subversão da Liberdade ou a Manutenção da Ordem", codigoDisciplina: "41130010005", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 6, disciplina: "A Humanização no Atendimento: O Uso das Tecnologias Leves em Saúde", codigoDisciplina: "41130010004", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 7, disciplina: "Inovações Tecnológicas como Estratégias para Saúde Mental na Educação", codigoDisciplina: "41130010073", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 8, disciplina: "Identidade Digital e Autenticidade", codigoDisciplina: "41130010137", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 9, disciplina: "Por Novas Linguagens para Expressão de Saúde: A Arte e a Criatividade", codigoDisciplina: "41130010109", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 10, disciplina: "Desconectado de Si Mesmo: A Automatização dos Processos e o Esgotamento Emocional no Trabalho", codigoDisciplina: "41130010037", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 11, disciplina: "Impactos das Mudanças no Século XXI para o Idoso", codigoDisciplina: "41130010070", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 12, disciplina: "A Captura da Subjetividade em Objeto pelo Mundo Digital", codigoDisciplina: "41130010001", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 13, disciplina: "A Emergência do Cuidado Mediante Crises em Saúde Coletiva", codigoDisciplina: "41130010002", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 14, disciplina: "Vulnerabilidade Social e Saúde Mental", codigoDisciplina: "41130010138", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 15, disciplina: "Ética: Inteligência Moral na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
    ],
  },
  "411-394": {
    sigla: "NR",
    curso: "Neurociência, Psicologia Positiva e Mindfulness",
    diaSemanaDefault: "quinta",
    paCh: 60,
    paAnosElegiveis: [2026, 2027, 2028],
    paCodigoPrefixo: "41130020002",
    carrossel: [
      { ordem: 1, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: null },
      { ordem: 2, disciplina: "Redução e Substituição de Maus Hábitos", codigoDisciplina: "41130010134", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 3, disciplina: "Detox Digital: “Likes” e “Curtidas” para Si Mesmo", codigoDisciplina: "41130010040", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 4, disciplina: "Mindfulness e Regulação Emocional: Principais Benefícios, Redução de Stress e Ansiedade", codigoDisciplina: "41130010088", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 5, disciplina: "Guia e Multiplicação de Práticas de Mindfulness e Autocompaixão", codigoDisciplina: "41130010067", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 6, disciplina: "Alta Performance e Equilíbrio Mental", codigoDisciplina: "41130010009", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 7, disciplina: "Mindfulness e Trabalho: Habilidades Psicossociais para o Desenvolvimento da Carreira com Sentido e Propósito", codigoDisciplina: "41130010089", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 8, disciplina: "Psicologia Positiva: Inteligência Emocional e Autoconsciência", codigoDisciplina: "41130010116", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 9, disciplina: "A Era da Ansiedade: Contribuições da Neurociência", codigoDisciplina: "41130010003", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 10, disciplina: "Felicidade e Suas Falácias Contemporâneas: Entre a Realização e a Ilusão", codigoDisciplina: "41130010050", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 11, disciplina: "O Século da Ansiedade, Depressão e Cansaço: Práticas de Saúde Emocional", codigoDisciplina: "41130010102", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 12, disciplina: "Positividade e Resiliência Humana: Anticorpos da Mente", codigoDisciplina: "41130010110", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 13, disciplina: "Interface Humano-Máquina: O Hibridismo e a Neurociência", codigoDisciplina: "41130010076", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 14, disciplina: "Consciência e Decisões: Uma Abordagem Neuroética", codigoDisciplina: "41130010033", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 15, disciplina: "Ética: Inteligência Moral na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
    ],
  },
  "411-491": {
    sigla: "GP",
    curso: "Gestão de Projetos, Jornada do Cliente e Metodologias Ágeis",
    diaSemanaDefault: "quarta",
    paCh: 60,
    paAnosElegiveis: [2026, 2027, 2028],
    paCodigoPrefixo: "41130020003",
    carrossel: [
      { ordem: 1, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: null },
      { ordem: 2, disciplina: "Design Sprint", codigoDisciplina: "41130010038", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 3, disciplina: "Liderança Ágil", codigoDisciplina: "41130010080", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 4, disciplina: "Planejamento e Controle de Projetos", codigoDisciplina: "41130010106", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 5, disciplina: "Gestão Contemporânea de Projetos", codigoDisciplina: "41130010055", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 6, disciplina: "Lean UX, Validação e Gestão Ágil", codigoDisciplina: "41130010144", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 7, disciplina: "Análise de Viabilidade em Ambientes Preditivos e Adaptativos", codigoDisciplina: "41130010012", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 8, disciplina: "Governança Ágil de Projetos, Programas e Portfólios", codigoDisciplina: "41130010064", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 9, disciplina: "Jornada Do Cliente", codigoDisciplina: "41130010077", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 10, disciplina: "Plataformas e Ferramentas Colaborativas para Gerenciamento de Projetos", codigoDisciplina: "41130010108", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 11, disciplina: "Project Management Office", codigoDisciplina: "41130010112", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 12, disciplina: "Ciência de Dados Aplicada ao Gerenciamento de Projetos", codigoDisciplina: "41130010028", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 13, disciplina: "Novos Tempos, Novas Lideranças", codigoDisciplina: "41130010097", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 14, disciplina: "Scrum, Kanban e Scrumban", codigoDisciplina: "41130010120", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 15, disciplina: "Ética: Inteligência Moral na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
    ],
  },
  "411-502": {
    sigla: "CD",
    curso: "Comunicação Digital, Branding e Storytelling",
    diaSemanaDefault: "quarta",
    paCh: 60,
    paAnosElegiveis: [2026, 2027, 2028],
    paCodigoPrefixo: "41130020004",
    carrossel: [
      { ordem: 1, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: null },
      { ordem: 2, disciplina: "Inbound Marketing: SEO e Copywriting", codigoDisciplina: "41130010071", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 3, disciplina: "Futurologia: Tendências para o Século 22", codigoDisciplina: "41130010053", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 4, disciplina: "Neurociência Aplicada a Negócios", codigoDisciplina: "41130010092", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 5, disciplina: "KPIs Estratégicos em Marketing", codigoDisciplina: "41130010078", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 6, disciplina: "Criação de Conteúdo Digital", codigoDisciplina: "41130010035", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 7, disciplina: "Fundamentos de Ciência de Dados e Big Data", codigoDisciplina: "41130010052", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 8, disciplina: "Marketing Digital e Community Management", codigoDisciplina: "41130010087", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 9, disciplina: "Lean UX, Validação e Gestão Ágil", codigoDisciplina: "41130010144", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 10, disciplina: "Jornada do Cliente", codigoDisciplina: "41130010077", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 11, disciplina: "Gestão de Marca: Branding", codigoDisciplina: "41130010060", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 12, disciplina: "Planejamento Estratégico em Comunicação", codigoDisciplina: "41130010107", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 13, disciplina: "Gestão da Comunicação em Mídias Digitais", codigoDisciplina: "41130010056", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 14, disciplina: "Storytelling: Histórias que Vendem", codigoDisciplina: "41130010123", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 15, disciplina: "Ética: Inteligência Moral na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
    ],
  },
  "411-506": {
    sigla: "IE",
    curso: "Espiritualidade, Carreira e Sentido da Vida",
    diaSemanaDefault: "quinta",
    paCh: 60,
    paAnosElegiveis: [2026, 2027, 2028],
    paCodigoPrefixo: "41130020005",
    carrossel: [
      { ordem: 1, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: null },
      { ordem: 2, disciplina: "Logoterapia e a Busca de Sentido da Vida", codigoDisciplina: "41130010086", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 3, disciplina: "Arte para Não Morrer de Verdade: Em Busca de um Sentido para a Vida", codigoDisciplina: "41130010017", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 4, disciplina: "Consciência, Espiritualidade e Educação: As Múltiplas Dimensões da Vida e a Busca por um Mundo Melhor", codigoDisciplina: "41130010034", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 5, disciplina: "Mindfulness e Regulação Emocional: Principais Benefícios, Redução de Stress e Ansiedade", codigoDisciplina: "41130010088", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 6, disciplina: "Novos Tempos, Novas Lideranças", codigoDisciplina: "41130010097", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 7, disciplina: "Lifelong Learning: Uma Vivência com Significado", codigoDisciplina: "41130010084", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 8, disciplina: "Legado: Vaidade ou Compromisso?", codigoDisciplina: "41130010079", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 9, disciplina: "Happycracia e os Perigos da Positividade Excessiva", codigoDisciplina: "41130010068", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 10, disciplina: "Espiritualidade para Organizações: O Que Devemos Aprender com Cristo, Gandhi e Buda", codigoDisciplina: "41130010044", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 11, disciplina: "Humano Esvaziado Humano: Virtudes Urgentes do Século XXI", codigoDisciplina: "41130010143", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 12, disciplina: "Bem-Estar é uma Habilidade", codigoDisciplina: "41130010020", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 13, disciplina: "Inteligência Espiritual no Século XXI", codigoDisciplina: "41130010075", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 14, disciplina: "Da Empregabilidade à Trabalhabilidade: O Que a Tecnologia Deixará aos Humanos", codigoDisciplina: "41130010036", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 15, disciplina: "Ética: Inteligência Moral na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
    ],
  },
  "411-722": {
    sigla: "UB",
    curso: "Urbanismo e o Futuro das Cidades: Planejamento Inteligente e Impactos Socioambientais",
    diaSemanaDefault: "quinta",
    paCh: 60,
    paAnosElegiveis: [2027, 2028],
    paCodigoPrefixo: "41130020006",
    carrossel: [
      { ordem: 1, disciplina: "Arquitetura Da Natureza", codigoDisciplina: "41130010016", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 2, disciplina: "Urbanismo Regenerativo", codigoDisciplina: "41130010129", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 3, disciplina: "Cidades E Desigualdades", codigoDisciplina: "41130010026", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 4, disciplina: "Questões Ambientais E Seus Impactos Nas Cidades", codigoDisciplina: "41130010117", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 5, disciplina: "Cidades Inteligentes E Inclusivas", codigoDisciplina: "41130010027", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 6, disciplina: "Governança: Desigualdade E Insurgência Urbana", codigoDisciplina: "41130010066", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 7, disciplina: "Mobilidade Urbana: Planejamento", codigoDisciplina: "41130010090", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 8, disciplina: "Arquitetura E Os Ícones Das Cidades", codigoDisciplina: "41130010015", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 9, disciplina: "Escalas De Planejamento", codigoDisciplina: "41130010043", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 10, disciplina: "Soluções Inteligentes Para As Cidades", codigoDisciplina: "41130010122", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 11, disciplina: "Ética: Inteligência Moral Na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 12, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: null },
      { ordem: 13, disciplina: "Mobilidade Urbana: Projetos", codigoDisciplina: "41130010091", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 14, disciplina: "Regulamentação E Desregulamentação", codigoDisciplina: "41130010118", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 15, disciplina: "Transformação Digital E Soluções Para As Cidades", codigoDisciplina: "41130010127", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
    ],
  },
  "411-807": {
    sigla: "MK",
    curso: "Marketing: Estratégias, Negócios Digitais e Experiência do Cliente",
    diaSemanaDefault: "quarta",
    paCh: 60,
    paAnosElegiveis: [2026, 2027, 2028],
    paCodigoPrefixo: "41130020007",
    carrossel: [
      { ordem: 1, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: null },
      { ordem: 2, disciplina: "Inbound Marketing: SEO e Copywriting", codigoDisciplina: "41130010071", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 3, disciplina: "Canais de Aquisição: Growth Hacking", codigoDisciplina: "41130010023", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 4, disciplina: "KPIs Estratégicos em Marketing", codigoDisciplina: "41130010078", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 5, disciplina: "Criação de Conteúdo Digital", codigoDisciplina: "41130010035", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 6, disciplina: "Tomada de Decisão Baseada em Dados - Customer Centricity", codigoDisciplina: "41130010126", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 7, disciplina: "Lean UX, Validação e Gestão Ágil", codigoDisciplina: "41130010144", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 8, disciplina: "User Experience: Engajando Usuários e Melhorando Performance", codigoDisciplina: "41130010130", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 9, disciplina: "Jornada do Cliente", codigoDisciplina: "41130010077", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 10, disciplina: "Gestão de Marca: Branding", codigoDisciplina: "41130010060", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 11, disciplina: "Design Sprint", codigoDisciplina: "41130010038", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 12, disciplina: "Planejamento Estratégico em Comunicação", codigoDisciplina: "41130010107", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 13, disciplina: "Gestão da Comunicação em Mídias Digitais", codigoDisciplina: "41130010056", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 14, disciplina: "Storytelling: Histórias que Vendem", codigoDisciplina: "41130010123", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 15, disciplina: "Ética: Inteligência Moral na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
    ],
  },
  "411-808": {
    sigla: "LA",
    curso: "Liderança Ágil: Pessoas, Projetos e Inovação",
    diaSemanaDefault: "quarta",
    paCh: 60,
    paAnosElegiveis: [2026, 2027, 2028],
    paCodigoPrefixo: "41130020008",
    carrossel: [
      { ordem: 1, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: null },
      { ordem: 2, disciplina: "Soft Skills para Negociação e Tomada de Decisão", codigoDisciplina: "41130010121", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 3, disciplina: "Liderança Ágil", codigoDisciplina: "41130010080", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 4, disciplina: "Gestão por Competências", codigoDisciplina: "41130010063", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 5, disciplina: "Comunicação Estratégica para Gestão de Pessoas", codigoDisciplina: "41130010031", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 6, disciplina: "Lean UX, Validação e Gestão Ágil", codigoDisciplina: "41130010144", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 7, disciplina: "Pessoas e Gestão Ágil de Negócios", codigoDisciplina: "41130010105", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 8, disciplina: "Governança Ágil de Projetos, Programas e Portfólios", codigoDisciplina: "41130010064", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 9, disciplina: "Motivação e Engajamento", codigoDisciplina: "41130010159", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 10, disciplina: "Liderança e Cultura Organizacional", codigoDisciplina: "41130010081", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 11, disciplina: "Design Sprint", codigoDisciplina: "41130010038", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 12, disciplina: "Gestão de Equipes Remotas", codigoDisciplina: "41130010059", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 13, disciplina: "Novos Tempos, Novas Lideranças", codigoDisciplina: "41130010097", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 14, disciplina: "Design Thinking e Inovação Ágil: Estimulando a Criatividade e a Experimentação", codigoDisciplina: "41130010039", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 15, disciplina: "Ética: Inteligência Moral na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
    ],
  },
  "411-941": {
    sigla: "NCE",
    curso: "Neurocomunicação: Estratégias para Narrativas de Impacto",
    diaSemanaDefault: "quinta",
    paCh: 60,
    paAnosElegiveis: [2026, 2027, 2028],
    paCodigoPrefixo: "41130020009",
    carrossel: [
      { ordem: 1, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: null },
      { ordem: 2, disciplina: "Inbound Marketing: SEO e Copywriting", codigoDisciplina: "41130010071", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 3, disciplina: "Experiência do Consumidor e Estratégias de Marketing Multissensorial", codigoDisciplina: "41130010139", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 4, disciplina: "Neurociência Aplicada a Negócios", codigoDisciplina: "41130010092", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 5, disciplina: "Psicologia da Comunicação: Uma Abordagem Neurocientífica", codigoDisciplina: "41130010115", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 6, disciplina: "Criação de Conteúdo Digital", codigoDisciplina: "41130010035", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 7, disciplina: "Fundamentos e Aplicações de Neurociência para Marketing", codigoDisciplina: "41130010140", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 8, disciplina: "Linguagem e Semiótica", codigoDisciplina: "41130010085", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 9, disciplina: "Neurodesign: Neurociência Aplicada à Comunicação Visual", codigoDisciplina: "41130010096", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 10, disciplina: "Jornada do Cliente", codigoDisciplina: "41130010077", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 11, disciplina: "Neurociência, Inteligência Emocional e Liderança", codigoDisciplina: "41130010141", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 12, disciplina: "Planejamento Estratégico em Comunicação", codigoDisciplina: "41130010107", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 13, disciplina: "Ferramentas de Neuromarketing", codigoDisciplina: "41130010142", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 14, disciplina: "Storytelling: Histórias que Vendem", codigoDisciplina: "41130010123", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 15, disciplina: "Ética: Inteligência Moral na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
    ],
  },
  "411-944": {
    sigla: "NAP",
    curso: "Neurociência Aplicada: Produtividade e Performance Humana",
    diaSemanaDefault: "quinta",
    paCh: 60,
    paAnosElegiveis: [2026, 2027, 2028],
    paCodigoPrefixo: "41130020010",
    carrossel: [
      { ordem: 1, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: null },
      { ordem: 2, disciplina: "Redução e Substituição de Maus Hábitos", codigoDisciplina: "41130010134", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 3, disciplina: "Neurociência Aplicada a Negócios", codigoDisciplina: "41130010092", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 4, disciplina: "Treinamentos, Protocolos e Práticas de Mindfulness: Saúde, Educação e Organizações", codigoDisciplina: "41130010128", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 5, disciplina: "Consciência e Decisões: Uma Abordagem Neuroética", codigoDisciplina: "41130010033", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 6, disciplina: "Neurociência Endócrina e Performance Humana", codigoDisciplina: "41130010095", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 7, disciplina: "Bem-Estar Psíquico, Saúde Mental e Sofrimento na Contemporaneidade", codigoDisciplina: "41130010021", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 8, disciplina: "Neurociência da Inspiração: Desvendando o Processo Criativo", codigoDisciplina: "41130010094", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 9, disciplina: "Neurociência da Felicidade", codigoDisciplina: "41130010093", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 10, disciplina: "Alta Performance e Equilíbrio Mental", codigoDisciplina: "41130010009", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 11, disciplina: "Comportamento Humano e Processos Cognitivos", codigoDisciplina: "41130010135", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 12, disciplina: "Bem-Estar é uma Habilidade", codigoDisciplina: "41130010020", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 13, disciplina: "Novos Tempos, Novas Lideranças", codigoDisciplina: "41130010097", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 14, disciplina: "A Era da Ansiedade: Contribuições da Neurociência", codigoDisciplina: "41130010003", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
      { ordem: 15, disciplina: "Ética: Inteligência Moral na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 10, liveFechamentoOffset: 17 },
    ],
  },
  "411-979": {
    sigla: "DG",
    curso: "Dinâmica Global: Geopolítica, Gestão de Riscos e Novas Oportunidades",
    diaSemanaDefault: "quarta",
    paCh: 60,
    paAnosElegiveis: [2027, 2028],
    paCodigoPrefixo: "41130020011",
    carrossel: [
      { ordem: 1, disciplina: "Admirável Futuro Novo", codigoDisciplina: "41130010007", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: null },
      { ordem: 2, disciplina: "Estrutura Financeira Internacional", codigoDisciplina: "41130010046", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 3, disciplina: "Organizações Internacionais", codigoDisciplina: "41130010104", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 4, disciplina: "Saúde Pública e Desafios Demográficos", codigoDisciplina: "41130010119", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 5, disciplina: "Comunicação Digital e Política Global", codigoDisciplina: "41130010030", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 6, disciplina: "Conflitos Internacionais, Guerras e Seus Impactos", codigoDisciplina: "41130010032", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 7, disciplina: "Liderança Estratégica Aplicada", codigoDisciplina: "41130010083", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 18 },
      { ordem: 8, disciplina: "Geoconhecimento", codigoDisciplina: "41130010054", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 9, disciplina: "Fronteiras Tecnológicas, Poder e Internet", codigoDisciplina: "41130010051", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 10, disciplina: "História da Humanidade e Dinâmicas Culturais", codigoDisciplina: "41130010069", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 11, disciplina: "Ordem e Direito Internacional", codigoDisciplina: "41130010103", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 12, disciplina: "O Futuro da Globalização e a Economia Moderna", codigoDisciplina: "41130010100", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 13, disciplina: "Teorias e Fundamentos da Política Internacional", codigoDisciplina: "41130010125", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 14, disciplina: "Análise de Risco Político-Global", codigoDisciplina: "41130010011", tipoOferta: "A", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
      { ordem: 15, disciplina: "Ética: Inteligência Moral na Era Digital", codigoDisciplina: "41130010048", tipoOferta: "C", ch: 20, liveEstudoCasoOffset: 9, liveFechamentoOffset: 16 },
    ],
  },
};
