/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSolicitacoesIndexRouteImport } from './routes/_authenticated/solicitacoes.index'
import { Route as AuthenticatedAprovacaoIndexRouteImport } from './routes/_authenticated/aprovacao.index'
import { Route as AuthenticatedSolicitacoesNovaRouteImport } from './routes/_authenticated/solicitacoes.nova'
import { Route as AuthenticatedSolicitacoesIdRouteImport } from './routes/_authenticated/solicitacoes.$id'
import { Route as AuthenticatedAprovacaoHistoricoRouteImport } from './routes/_authenticated/aprovacao.historico'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSolicitacoesIndexRoute =
  AuthenticatedSolicitacoesIndexRouteImport.update({
    id: '/solicitacoes/',
    path: '/solicitacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAprovacaoIndexRoute =
  AuthenticatedAprovacaoIndexRouteImport.update({
    id: '/aprovacao/',
    path: '/aprovacao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitacoesNovaRoute =
  AuthenticatedSolicitacoesNovaRouteImport.update({
    id: '/solicitacoes/nova',
    path: '/solicitacoes/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitacoesIdRoute =
  AuthenticatedSolicitacoesIdRouteImport.update({
    id: '/solicitacoes/$id',
    path: '/solicitacoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAprovacaoHistoricoRoute =
  AuthenticatedAprovacaoHistoricoRouteImport.update({
    id: '/aprovacao/historico',
    path: '/aprovacao/historico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aprovacao/historico': typeof AuthenticatedAprovacaoHistoricoRoute
  '/solicitacoes/$id': typeof AuthenticatedSolicitacoesIdRoute
  '/solicitacoes/nova': typeof AuthenticatedSolicitacoesNovaRoute
  '/aprovacao/': typeof AuthenticatedAprovacaoIndexRoute
  '/solicitacoes/': typeof AuthenticatedSolicitacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aprovacao/historico': typeof AuthenticatedAprovacaoHistoricoRoute
  '/solicitacoes/$id': typeof AuthenticatedSolicitacoesIdRoute
  '/solicitacoes/nova': typeof AuthenticatedSolicitacoesNovaRoute
  '/aprovacao': typeof AuthenticatedAprovacaoIndexRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/aprovacao/historico': typeof AuthenticatedAprovacaoHistoricoRoute
  '/_authenticated/solicitacoes/$id': typeof AuthenticatedSolicitacoesIdRoute
  '/_authenticated/solicitacoes/nova': typeof AuthenticatedSolicitacoesNovaRoute
  '/_authenticated/aprovacao/': typeof AuthenticatedAprovacaoIndexRoute
  '/_authenticated/solicitacoes/': typeof AuthenticatedSolicitacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aprovacao/historico'
    | '/solicitacoes/$id'
    | '/solicitacoes/nova'
    | '/aprovacao/'
    | '/solicitacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aprovacao/historico'
    | '/solicitacoes/$id'
    | '/solicitacoes/nova'
    | '/aprovacao'
    | '/solicitacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/aprovacao/historico'
    | '/_authenticated/solicitacoes/$id'
    | '/_authenticated/solicitacoes/nova'
    | '/_authenticated/aprovacao/'
    | '/_authenticated/solicitacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solicitacoes/': {
      id: '/_authenticated/solicitacoes/'
      path: '/solicitacoes'
      fullPath: '/solicitacoes/'
      preLoaderRoute: typeof AuthenticatedSolicitacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprovacao/': {
      id: '/_authenticated/aprovacao/'
      path: '/aprovacao'
      fullPath: '/aprovacao/'
      preLoaderRoute: typeof AuthenticatedAprovacaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes/nova': {
      id: '/_authenticated/solicitacoes/nova'
      path: '/solicitacoes/nova'
      fullPath: '/solicitacoes/nova'
      preLoaderRoute: typeof AuthenticatedSolicitacoesNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes/$id': {
      id: '/_authenticated/solicitacoes/$id'
      path: '/solicitacoes/$id'
      fullPath: '/solicitacoes/$id'
      preLoaderRoute: typeof AuthenticatedSolicitacoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprovacao/historico': {
      id: '/_authenticated/aprovacao/historico'
      path: '/aprovacao/historico'
      fullPath: '/aprovacao/historico'
      preLoaderRoute: typeof AuthenticatedAprovacaoHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAprovacaoHistoricoRoute: typeof AuthenticatedAprovacaoHistoricoRoute
  AuthenticatedSolicitacoesIdRoute: typeof AuthenticatedSolicitacoesIdRoute
  AuthenticatedSolicitacoesNovaRoute: typeof AuthenticatedSolicitacoesNovaRoute
  AuthenticatedAprovacaoIndexRoute: typeof AuthenticatedAprovacaoIndexRoute
  AuthenticatedSolicitacoesIndexRoute: typeof AuthenticatedSolicitacoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAprovacaoHistoricoRoute: AuthenticatedAprovacaoHistoricoRoute,
  AuthenticatedSolicitacoesIdRoute: AuthenticatedSolicitacoesIdRoute,
  AuthenticatedSolicitacoesNovaRoute: AuthenticatedSolicitacoesNovaRoute,
  AuthenticatedAprovacaoIndexRoute: AuthenticatedAprovacaoIndexRoute,
  AuthenticatedSolicitacoesIndexRoute: AuthenticatedSolicitacoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
